# Remap the prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Change splitting keys
bind v split-window -h
bind h split-window -v

# Faster navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Make reloading config simple
bind r source-file ~/.tmux.conf

# Set default terminal style
set -g default-terminal "screen-256color"

# Set titles to show position
set -g set-titles on

# Start counting tmux windows at 1 instead of 0
set -g base-index 1

# Enable mouse interaction with panes
set -g mouse on

# Ensure the home & end keys work as expected
#bind -n End send-key C-e
#bind -n Home send-key C-a

# Visual monitoring
setw -g monitor-activity on
set -g visual-activity on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

# My Plugins
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# Autostart tmux at boot via continuum
# set -g @continuum-boot 'on'

# Restore the last saved environment
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
